from pydantic import BaseModel, Field
from typing import Optional
from enum import Enum

class RiskLevel(str, Enum):
    CRITICAL = "Critical"
    HIGH = "High"
    MEDIUM = "Medium"
    LOW = "Low"

class RecommendedAction(str, Enum):
    REDACT = "Redact"
    VERIFY = "Verify"
    REVIEW = "Review"

class Observation(BaseModel):
    question: str = Field(..., description="The original question asked to the AI")
    model_answer: str = Field(..., description="The answer generated by the AI model that needs auditing")

class Action(BaseModel):
    is_hallucination: bool = Field(..., description="True if the model answer contains any fabrication or factual error")
    confidence: float = Field(..., description="Confidence in the detection (0.0 to 1.0)")
    risk_level: RiskLevel = Field(..., description="The severity of the potential misinformation")
    recommended_action: RecommendedAction = Field(..., description="The suggested next step to handle this content")
    reasoning: str = Field(..., description="Brief explanation for the classification")

class Reward(BaseModel):
    score: float = Field(..., description="Deterministic reward score from 0.0 to 1.0")
    details: str = Field(..., description="Breakdown of the reward calculation")
